import type { GrammarLesson } from '../types'

export const A1_LESSONS: GrammarLesson[] = [
  {
    id: 'a1-to-be',
    level: 'A1',
    title: 'To be: am / is / are',
    gist: 'Глагол be — «быть, являться». Без него не собрать почти ни одно простое предложение: кто ты, где ты, какой это.',
    form: 'I am · he/she/it is · you/we/they are · отрицание: am/is/are + not · вопрос: Be + подлежащее?',
    rules: [
      'Be связывает подлежащее с описанием, местом или возрастом: I am tired. She is a doctor. They are at home.',
      'Сокращения: I\'m, he\'s, she\'s, it\'s, we\'re, you\'re, they\'re. В отрицании: isn\'t, aren\'t (I\'m not без сокращения isn\'t).',
      'Вопрос: перестановка be вперёд — Are you ready? Where is the station?',
      'В русском «это» часто опускается. В английском be почти всегда нужен: This is my brother. (не This my brother.)',
    ],
    examples: [
      { en: 'I am a student.', ru: 'Я студент.' },
      { en: 'She isn\'t at work today.', ru: 'Её сегодня нет на работе.' },
      { en: 'Are they from Spain?', ru: 'Они из Испании?' },
      { en: 'It\'s cold in here.', ru: 'Здесь холодно.' },
      { en: 'Where are you?', ru: 'Где ты?' },
    ],
    pitfalls: [
      'Пропуск be: He teacher → He is a teacher.',
      'He are / they is — согласование: he/she/it → is, I → am, остальные → are.',
      'It\'s = it is. Its без апострофа — притяжательное «его/её» (у вещи).',
    ],
    seeAlso: ['a1-there-is', 'a1-pronouns', 'a1-present-simple'],
  },
  {
    id: 'a1-have-got',
    level: 'A1',
    title: 'Have got: владение',
    gist: 'Have got — «иметь, быть у кого-то». На A1 это основной способ сказать про вещи, семью, проблемы.',
    form: 'I/you/we/they have got · he/she/it has got · отрицание: haven\'t / hasn\'t got · вопрос: Have/Has + подлежащее + got?',
    rules: [
      'Значение: обладание и отношения — I\'ve got a car. She\'s got two brothers.',
      'Got здесь не «получил», а часть устойчивой британской конструкции. В американском чаще I have a car.',
      'Краткий ответ: Yes, I have. / No, she hasn\'t. — без got.',
      'Have got не ставят в прошедшее как *had got* в значении «имел»: в прошлом — had.',
    ],
    examples: [
      { en: 'I\'ve got a new phone.', ru: 'У меня новый телефон.' },
      { en: 'He hasn\'t got any time.', ru: 'У него нет времени.' },
      { en: 'Have you got a minute?', ru: 'Есть минутка?' },
      { en: 'We\'ve got a problem.', ru: 'У нас проблема.' },
      { en: 'She\'s got brown eyes.', ru: 'У неё карие глаза.' },
    ],
    pitfalls: [
      'He have got → He has got.',
      'I am have → I have / I\'ve got (be здесь не нужен).',
      'Вопрос Do you have got? — либо Have you got?, либо Do you have?',
    ],
    seeAlso: ['a1-to-be', 'a1-some-any', 'a1-present-simple'],
  },
  {
    id: 'a1-present-simple',
    level: 'A1',
    title: 'Present Simple',
    gist: 'Настоящее простое — факты, привычки, расписание. Это базовая «сейчас-вообще» форма, не про действие в эту секунду.',
    form: 'I/you/we/they + V · he/she/it + V-s · do/does + not · вопрос: Do/Does + подлежащее + V?',
    rules: [
      'Употребление: регулярность (I work every day), факты (Water boils at 100°C), расписание (The train leaves at 9).',
      'Третье лицо единственного числа: +s / +es (watches, goes, studies). Have → has.',
      'Отрицание и вопрос только через do/does: She doesn\'t like tea. Does he live here? Смысловой глагол без -s.',
      'Наречия частоты обычно перед смысловым глаголом, но после be: I always walk. She is never late.',
    ],
    examples: [
      { en: 'I live in Berlin.', ru: 'Я живу в Берлине.' },
      { en: 'He works from home.', ru: 'Он работает из дома.' },
      { en: 'She doesn\'t drink coffee.', ru: 'Она не пьёт кофе.' },
      { en: 'Do you speak English?', ru: 'Ты говоришь по-английски?' },
      { en: 'The shop opens at eight.', ru: 'Магазин открывается в восемь.' },
    ],
    pitfalls: [
      'He work → He works. В утверждении -s обязателен.',
      'Does he works? → Does he work? После does глагол голый.',
      'I am work → I work. Present Simple без be (кроме самого be).',
    ],
    seeAlso: ['a1-present-continuous', 'a2-word-order', 'a1-to-be'],
  },
  {
    id: 'a1-present-continuous',
    level: 'A1',
    title: 'Present Continuous',
    gist: 'Настоящее длительное — действие прямо сейчас или временная ситуация вокруг текущего момента.',
    form: 'am/is/are + V-ing · отрицание: am/is/are + not + V-ing · вопрос: Be + подлежащее + V-ing?',
    rules: [
      'Сейчас: I\'m cooking. Временное: She\'s staying with us this week.',
      '-ing: make → making, sit → sitting, lie → lying. Смотри на немое e и удвоение согласной.',
      'Глаголы состояния обычно не ставят в Continuous: know, like, want, believe, have (в значении «иметь»).',
      'Не путать с Present Simple: I live here (постоянно) vs I\'m living here (пока, временно).',
    ],
    examples: [
      { en: 'I\'m reading a book right now.', ru: 'Я сейчас читаю книгу.' },
      { en: 'They aren\'t working today.', ru: 'Они сегодня не работают.' },
      { en: 'Is it raining?', ru: 'Идёт дождь?' },
      { en: 'He\'s studying Italian this year.', ru: 'В этом году он учит итальянский.' },
      { en: 'Look, the bus is coming.', ru: 'Смотри, автобус подходит.' },
    ],
    pitfalls: [
      'I reading → I\'m reading. Без be форма не собирается.',
      'I am knowing → I know. Состояния не для Continuous.',
      'What do you doing? → What are you doing?',
    ],
    seeAlso: ['a1-present-simple', 'a1-to-be', 'b1-future-forms'],
  },
  {
    id: 'a1-articles-plurals',
    level: 'A1',
    title: 'A / an и множественное число',
    gist: 'A/an — «один, какой-то» перед исчисляемым в единственном числе. Множественное: +s/+es, без артикля для «вообще».',
    form: 'a + согласный звук (a book) · an + гласный звук (an apple) · множественное: +s / +es / -ies',
    rules: [
      'A/an зависит от звука, не от буквы: a university [ju:], an hour [aʊə].',
      'Перед профессией и ролью артикль нужен: She is a teacher. He is an engineer.',
      'Множественное: book → books, box → boxes, city → cities, child → children, person → people, man → men.',
      'The — «тот самый, уже известный». На A1: the sun, the door (конкретная). Подробнее — на B1.',
    ],
    examples: [
      { en: 'This is a cat.', ru: 'Это кот.' },
      { en: 'I need an umbrella.', ru: 'Мне нужен зонт.' },
      { en: 'She is a doctor.', ru: 'Она врач.' },
      { en: 'I like apples.', ru: 'Я люблю яблоки. (вообще)' },
      { en: 'The apples on the table are green.', ru: 'Яблоки на столе зелёные. (конкретные)' },
    ],
    pitfalls: [
      'She is teacher → She is a teacher.',
      'An university → a university (звук [j]).',
      'A informations → information неисчисляемое, без a и без -s.',
    ],
    seeAlso: ['a1-this-that', 'a2-countable', 'b1-articles'],
  },
  {
    id: 'a1-this-that',
    level: 'A1',
    title: 'This / that / these / those',
    gist: 'Указательные слова: близко vs далеко, одно vs много. Заменяют жест «вот это / вон то».',
    form: 'близко: this (ед.) / these (мн.) · далеко: that (ед.) / those (мн.)',
    rules: [
      'This/these — рядом с говорящим; that/those — дальше, или уже упомянутое.',
      'Перед существительным: this book, those cars. Без существительного: What is this?',
      'That часто указывает на ситуацию: That\'s a good idea. That\'s interesting.',
      'Во множественном глагол are: These are my keys. Those were cheap.',
    ],
    examples: [
      { en: 'This is my bag.', ru: 'Это моя сумка. (вот эта)' },
      { en: 'That restaurant is expensive.', ru: 'Тот ресторан дорогой.' },
      { en: 'Are these your keys?', ru: 'Это твои ключи?' },
      { en: 'I don\'t like those shoes.', ru: 'Мне не нравятся те туфли.' },
      { en: 'That\'s my brother over there.', ru: 'Вон там мой брат.' },
    ],
    pitfalls: [
      'This are → These are. Согласование числа.',
      'This people → These people (people уже множественное).',
      'That books → Those books.',
    ],
    seeAlso: ['a1-to-be', 'a1-articles-plurals', 'a1-there-is'],
  },
  {
    id: 'a1-pronouns',
    level: 'A1',
    title: 'Местоимения и притяжательные',
    gist: 'Кто делает (I, she) vs кого/кому (me, her) vs чьё (my, her, mine). Путаница здесь ломает каждое предложение.',
    form: 'I–me–my–mine · you–you–your–yours · he–him–his–his · she–her–her–hers · it–it–its–— · we–us–our–ours · they–them–their–theirs',
    rules: [
      'Подлежащее: I, he, she, we, they. Дополнение: me, him, her, us, them — после глагола и предлога.',
      'My book — перед существительным. Mine — само, без существительного: This is mine.',
      'Its — «его/её» у вещи, без апострофа. It\'s = it is / it has.',
      'Whose is this? — It\'s Tom\'s. / It\'s his.',
    ],
    examples: [
      { en: 'She likes him.', ru: 'Она ему нравится / она его любит.' },
      { en: 'This is my phone. That one is yours.', ru: 'Это мой телефон. Тот — твой.' },
      { en: 'Can you help us?', ru: 'Можешь нам помочь?' },
      { en: 'The dog ate its food.', ru: 'Собака съела свою еду.' },
      { en: 'Their house is near ours.', ru: 'Их дом рядом с нашим.' },
    ],
    pitfalls: [
      'Me live here → I live here. В начале предложения — подлежащее I.',
      'This is mine book → This is my book. Или This is mine. без book.',
      'It\'s name → Its name.',
    ],
    seeAlso: ['a1-to-be', 'a1-have-got', 'a1-this-that'],
  },
  {
    id: 'a1-can',
    level: 'A1',
    title: 'Can: умение и разрешение',
    gist: 'Can — умение («умею») и разрешение («можно»). Форма не меняется: без to, без -s, без do.',
    form: 'подлежащее + can + V · can\'t / cannot · вопрос: Can + подлежащее + V?',
    rules: [
      'Умение: I can swim. Разрешение: Can I open the window? Невозможность: I can\'t come.',
      'После can всегда голый инфинитив: can go, не can to go и не can going.',
      'Для всех лиц одна форма: she can, не she cans.',
      'Вежливая просьба: Can you help me? На A2 появится could как более мягкий вариант.',
    ],
    examples: [
      { en: 'I can speak a little German.', ru: 'Я немного говорю по-немецки.' },
      { en: 'She can\'t drive.', ru: 'Она не умеет водить.' },
      { en: 'Can I use your charger?', ru: 'Можно взять зарядку?' },
      { en: 'Can you see the screen?', ru: 'Тебе видно экран?' },
      { en: 'He can run fast.', ru: 'Он быстро бегает.' },
    ],
    pitfalls: [
      'I can to swim → I can swim.',
      'She cans cook → She can cook.',
      'Do you can…? → Can you…? Do с модальными не ставят.',
    ],
    seeAlso: ['a1-present-simple', 'a2-modals-obligation', 'b1-modals-deduction'],
  },
  {
    id: 'a1-there-is',
    level: 'A1',
    title: 'There is / there are',
    gist: 'Конструкция «есть, находится» для введения объекта в пространство. Не путать с they are.',
    form: 'there is + ед. · there are + мн. · isn\'t / aren\'t · Is there…? / Are there…?',
    rules: [
      'There is a park near here. There are two shops on this street.',
      'Согласование с первым существительным: There is a table and two chairs. (часто is, потому что a table).',
      'Вопрос о наличии: Is there a pharmacy nearby? Are there any questions?',
      'There = «имеется», they = «они». There are my keys? неверно для «это мои ключи» — These are my keys.',
    ],
    examples: [
      { en: 'There is a cat on the sofa.', ru: 'На диване кот.' },
      { en: 'There aren\'t any buses after midnight.', ru: 'После полуночи автобусов нет.' },
      { en: 'Is there a toilet here?', ru: 'Здесь есть туалет?' },
      { en: 'There are three people in the room.', ru: 'В комнате трое.' },
      { en: 'There isn\'t much time.', ru: 'Времени мало.' },
    ],
    pitfalls: [
      'It is a book on the table → There is a book on the table. (введение объекта)',
      'There is many people → There are many people.',
      'They are a cinema in town → There is a cinema…',
    ],
    seeAlso: ['a1-to-be', 'a1-some-any', 'a1-prepositions'],
  },
  {
    id: 'a1-past-simple',
    level: 'A1',
    title: 'Past Simple: was/were и правильные глаголы',
    gist: 'Прошедшее простое — законченное действие в прошлом. На A1: be в прошедшем и правильные глаголы на -ed.',
    form: 'I/he/she/it was · you/we/they were · правильные: V-ed · вопрос/отрицание: did + V (не be)',
    rules: [
      'Was/were — прошедшее от be: I was tired. They were at home. Вопрос: Were you there?',
      'Правильные: work → worked, play → played, stop → stopped, try → tried.',
      'Для всех лиц одна форма прошедшего: I/he/they worked. -s нет.',
      'Did не ставят с was/were: Did you were? неверно. Were you? / Did you go?',
    ],
    examples: [
      { en: 'I was in London last year.', ru: 'В прошлом году я был в Лондоне.' },
      { en: 'We weren\'t hungry.', ru: 'Мы не были голодны.' },
      { en: 'She watched a film yesterday.', ru: 'Вчера она посмотрела фильм.' },
      { en: 'Did you call him?', ru: 'Ты ему звонил?' },
      { en: 'They didn\'t wait.', ru: 'Они не стали ждать.' },
    ],
    pitfalls: [
      'I did went → I went / I didn\'t go. После did — первая форма.',
      'He was go → He went. Was не клеят к смысловому глаголу.',
      'Did you were happy? → Were you happy?',
    ],
    seeAlso: ['a2-past-simple-irregular', 'a2-past-continuous', 'a1-to-be'],
  },
  {
    id: 'a1-going-to',
    level: 'A1',
    title: 'Going to: планы и очевидное будущее',
    gist: 'Be + going to + глагол — намерение или то, что уже видно по ситуации. Базовое «будущее» на A1.',
    form: 'am/is/are + going to + V · not going to · вопрос: Be + подлежащее + going to + V?',
    rules: [
      'План: I\'m going to cook tonight. (уже решил)',
      'Предсказание по уликам: Look at those clouds. It\'s going to rain.',
      'Going to не равно going в значении «иду»: I\'m going to the shop (направление) vs I\'m going to buy milk (намерение).',
      'Will появится на A2 как другое будущее — обещание, решение в момент речи.',
    ],
    examples: [
      { en: 'I\'m going to start a new course.', ru: 'Я собираюсь начать новый курс.' },
      { en: 'She isn\'t going to come.', ru: 'Она не собирается приходить.' },
      { en: 'Are you going to watch the match?', ru: 'Будешь смотреть матч?' },
      { en: 'It\'s going to be cold tomorrow.', ru: 'Завтра будет холодно.' },
      { en: 'We\'re going to move in June.', ru: 'Мы переезжаем в июне.' },
    ],
    pitfalls: [
      'I going to… → I\'m going to… Нужен be.',
      'I\'m going to going → I\'m going to go.',
      'He going rain → It\'s going to rain. (погода — it)',
    ],
    seeAlso: ['a1-present-continuous', 'a2-will-going-to', 'b1-future-forms'],
  },
  {
    id: 'a1-prepositions',
    level: 'A1',
    title: 'Предлоги in / on / at',
    gist: 'Три самых частых предлога времени и места. На A1 достаточно сетки «в / на / у точки», без исключений на десять страниц.',
    form: 'время: at + час, on + день/дата, in + месяц/год/часть дня · место: at точка, on поверхность, in внутри',
    rules: [
      'Время: at 7 o\'clock, at night, at the weekend (BrE); on Monday, on 5 May; in July, in 2020, in the morning.',
      'Место: in a room / in London; on the table / on the wall; at the station / at home / at work.',
      'At home, at work, at school — без артикля в этих устойчивых сочетаниях.',
      'On the bus / on the train — «на транспорте», даже если ты внутри.',
    ],
    examples: [
      { en: 'The meeting is at three.', ru: 'Встреча в три.' },
      { en: 'I was born in March.', ru: 'Я родился в марте.' },
      { en: 'See you on Friday.', ru: 'Увидимся в пятницу.' },
      { en: 'The keys are on the table.', ru: 'Ключи на столе.' },
      { en: 'She\'s at the airport.', ru: 'Она в аэропорту. (точка)' },
    ],
    pitfalls: [
      'In Friday → on Friday. Дни недели — on.',
      'In home → at home.',
      'At the morning → in the morning. Но at night.',
    ],
    seeAlso: ['a1-there-is', 'a1-present-simple', 'b1-articles'],
  },
  {
    id: 'a1-some-any',
    level: 'A1',
    title: 'Some / any',
    gist: 'Some — «несколько / немного» в утверждениях. Any — в вопросах и отрицаниях. Работает и с исчисляемыми, и с неисчисляемыми.',
    form: 'утверждение: some · вопрос и not: any · вежливое предложение: some',
    rules: [
      'I\'ve got some questions. There is some milk. — утверждение.',
      'Have you got any questions? I haven\'t got any milk. — вопрос и отрицание.',
      'Предложение и просьба часто с some: Would you like some tea? Can I have some water?',
      'Someone / anyone, something / anything устроены так же: I saw someone. I didn\'t see anyone.',
    ],
    examples: [
      { en: 'I bought some apples.', ru: 'Я купил яблок.' },
      { en: 'We don\'t have any bread.', ru: 'У нас нет хлеба.' },
      { en: 'Is there any news?', ru: 'Есть новости?' },
      { en: 'Would you like some coffee?', ru: 'Хочешь кофе?' },
      { en: 'I didn\'t tell anyone.', ru: 'Я никому не сказал.' },
    ],
    pitfalls: [
      'I haven\'t some money → I haven\'t got any money.',
      'Any в утверждении в значении «любой» — уже A2+: Any student can join. На A1 в утверждениях бери some.',
      'Some water? в голом вопросе чаще Is there any water? Вежливое Can I have some water? — ок.',
    ],
    seeAlso: ['a1-have-got', 'a1-there-is', 'a2-countable'],
  },
]
