import type { GrammarLesson } from '../types'

export const A2_LESSONS: GrammarLesson[] = [
  {
    id: 'a2-past-simple-irregular',
    level: 'A2',
    title: 'Past Simple: неправильные глаголы',
    gist: 'Большая часть частотных глаголов не берёт -ed: go → went, have → had, see → saw. Форма одна для всех лиц; в вопросе и отрицании — did + первая форма.',
    form: 'утверждение: V2 (went, saw) · отрицание: didn\'t + V1 · вопрос: Did + подлежащее + V1?',
    rules: [
      'Список ядра: be–was/were, have–had, do–did, go–went, get–got, make–made, see–saw, come–came, take–took, know–knew, think–thought, say–said, tell–told, give–gave, find–found.',
      'Did «съедает» прошедшее: Did you go? He didn\'t see. Никогда *didn\'t went*.',
      'Краткий ответ: Yes, I did. / No, she didn\'t.',
      'Маркеры: yesterday, last week, in 2019, ago — Past Simple, не Present Perfect.',
    ],
    examples: [
      { en: 'I went home early.', ru: 'Я рано ушёл домой.' },
      { en: 'She didn\'t tell me.', ru: 'Она мне не сказала.' },
      { en: 'Did you see the email?', ru: 'Ты видел письмо?' },
      { en: 'We had lunch at one.', ru: 'Мы пообедали в час.' },
      { en: 'He made a mistake.', ru: 'Он ошибся.' },
    ],
    pitfalls: [
      'I didn\'t went → I didn\'t go.',
      'Did you saw? → Did you see?',
      'I have seen him yesterday → I saw him yesterday. С yesterday — Past Simple.',
    ],
    seeAlso: ['a1-past-simple', 'a2-present-perfect', 'b1-pp-vs-past'],
  },
  {
    id: 'a2-past-continuous',
    level: 'A2',
    title: 'Past Continuous',
    gist: 'Прошедшее длительное — фон: «в тот момент шло». Часто рядом с Past Simple: одно действие прерывает другое.',
    form: 'was/were + V-ing · wasn\'t / weren\'t · Was/Were + подлежащее + V-ing?',
    rules: [
      'Длительность в прошлом: At 8 I was cooking. While they were talking, I left.',
      'Связка с Past Simple: I was walking home when it started to rain. (фон + событие)',
      'When + Past Simple; while + Past Continuous — типичный каркас.',
      'Состояния (know, want, like) почти не ставят в Continuous и в прошлом тоже.',
    ],
    examples: [
      { en: 'She was sleeping at midnight.', ru: 'В полночь она спала.' },
      { en: 'We weren\'t watching TV.', ru: 'Мы не смотрели телевизор.' },
      { en: 'What were you doing at five?', ru: 'Что ты делал в пять?' },
      { en: 'I was working when he called.', ru: 'Я работал, когда он позвонил.' },
      { en: 'They were still waiting.', ru: 'Они всё ещё ждали.' },
    ],
    pitfalls: [
      'I was go → I was going / I went. Нужно -ing или просто Past Simple.',
      'When I was a child I was living… — для постоянных фактов чаще I lived.',
      'He was knowing → He knew.',
    ],
    seeAlso: ['a1-past-simple', 'a2-past-simple-irregular', 'b1-past-perfect'],
  },
  {
    id: 'a2-present-perfect',
    level: 'A2',
    title: 'Present Perfect: введение',
    gist: 'Have/has + третья форма — связь прошлого с настоящим: опыт, результат «уже/ещё», жизнь до сейчас. Не перевод «я сделал вчера».',
    form: 'have/has + V3 · haven\'t / hasn\'t · Have/Has + подлежащее + V3?',
    rules: [
      'Опыт: I\'ve been to Japan. Have you ever…? I\'ve never…',
      'Результат сейчас: She\'s lost her keys. (ключей нет). I\'ve already eaten. He hasn\'t arrived yet.',
      'Just / already / yet / ever / never — типичные спутники. Yesterday / last year — обычно Past Simple.',
      'Been = «съездил и вернулся»; gone = «уехал, его нет»: He\'s gone to Italy.',
    ],
    examples: [
      { en: 'I\'ve finished the report.', ru: 'Я закончил отчёт. (вот он)' },
      { en: 'Have you ever tried sushi?', ru: 'Ты когда-нибудь пробовал суши?' },
      { en: 'She hasn\'t called yet.', ru: 'Она ещё не звонила.' },
      { en: 'We\'ve just arrived.', ru: 'Мы только что приехали.' },
      { en: 'He\'s gone out.', ru: 'Он вышел. (его нет)' },
    ],
    pitfalls: [
      'I have seen him yesterday → I saw him yesterday.',
      'I am lived here for 3 years → I\'ve lived here for 3 years. (опыт/срок до сейчас)',
      'I have never went → I have never gone / been.',
    ],
    seeAlso: ['a2-past-simple-irregular', 'b1-pp-vs-past', 'b1-pp-continuous'],
  },
  {
    id: 'a2-will-going-to',
    level: 'A2',
    title: 'Will vs going to',
    gist: 'Два базовых будущих. Will — решение в момент речи, обещание, прогноз «вообще». Going to — план заранее или очевидное по ситуации.',
    form: 'will / won\'t + V · am/is/are going to + V',
    rules: [
      'Will: I\'ll get it. (решил сейчас), I\'ll help you. (обещание), I think it\'ll be fine. (мнение).',
      'Going to: We\'re going to move in May. Look — it\'s going to crash.',
      'В разговоре они часто пересекаются; важнее намерение (уже решил vs только что решил).',
      'Shall I…? — предложение помощи (BrE). Shall we go? — «пойдём?»',
    ],
    examples: [
      { en: 'It\'s cold. I\'ll close the window.', ru: 'Холодно. Я закрою окно. (сейчас решил)' },
      { en: 'I\'m going to start gym in January.', ru: 'С января иду в зал. (план)' },
      { en: 'She won\'t like this.', ru: 'Ей это не понравится.' },
      { en: 'Look at the sky. It\'s going to snow.', ru: 'Смотри на небо. Снег пойдёт.' },
      { en: 'I\'ll email you tonight.', ru: 'Вечером напишу. (обещание)' },
    ],
    pitfalls: [
      'I will to go → I will go. После will нет to.',
      'Путать план и спонтанность: заранее купленные билеты — going to / Present Continuous, не will «наугад».',
      'Will в условных первого типа — в главной части: If it rains, I\'ll stay. Не *If it will rain*.',
    ],
    seeAlso: ['a1-going-to', 'a2-first-conditional', 'b1-future-forms'],
  },
  {
    id: 'a2-comparatives',
    level: 'A2',
    title: 'Сравнительная и превосходная степень',
    gist: 'Сравнение двух и «самый». Короткие прилагательные: -er / -est. Длинные: more / the most. Исключения: good, bad, far.',
    form: 'short: -er than / the -est · long: more … than / the most … · as … as',
    rules: [
      'Один слог: cheap → cheaper → the cheapest. Два слога на -y: easy → easier → the easiest.',
      'Длинные: more expensive, the most interesting. Не *expensiver*.',
      'Good → better → the best. Bad → worse → the worst. Far → farther/further.',
      'Равенство: as tall as. Неравенство: not as … as. Than, не then.',
    ],
    examples: [
      { en: 'This café is cheaper than that one.', ru: 'Это кафе дешевле того.' },
      { en: 'She is the tallest in the team.', ru: 'Она самая высокая в команде.' },
      { en: 'The film was more boring than the book.', ru: 'Фильм был скучнее книги.' },
      { en: 'Today is worse than yesterday.', ru: 'Сегодня хуже, чем вчера.' },
      { en: 'He isn\'t as fast as you.', ru: 'Он не такой быстрый, как ты.' },
    ],
    pitfalls: [
      'More bigger → bigger. Не удваивай степень.',
      'Then вместо than: bigger then me → bigger than me.',
      'The most cheap → the cheapest.',
    ],
    seeAlso: ['a1-articles-plurals', 'a2-word-order', 'b1-articles'],
  },
  {
    id: 'a2-countable',
    level: 'A2',
    title: 'Исчисляемые и неисчисляемые: much / many',
    gist: 'Можно посчитать (apples) vs вещество/абстракция (water, time, advice). От этого зависят a, many, much, a few, a little.',
    form: 'исчисл.: many / a few / few + мн. · неисчисл.: much / a little / little + ед. · оба: a lot of / lots of',
    rules: [
      'Many books, much time. A lot of работает с обоими и звучит естественнее в утверждении.',
      'Much/many чаще в вопросах и отрицаниях: How much is it? There isn\'t much milk.',
      'A few / a little — «немного, но есть». Few / little без a — «мало, почти нет» (негативнее).',
      'Advice, information, news, furniture, luggage — неисчисляемые. A piece of advice, не *an advice*.',
    ],
    examples: [
      { en: 'How many people were there?', ru: 'Сколько там было людей?' },
      { en: 'There isn\'t much traffic.', ru: 'Трафика почти нет.' },
      { en: 'I\'ve got a lot of work.', ru: 'У меня много работы.' },
      { en: 'We have a little time left.', ru: 'У нас ещё немного времени.' },
      { en: 'She gave me some useful advice.', ru: 'Она дала полезный совет. (advice без -s)' },
    ],
    pitfalls: [
      'Many money / much people — наоборот: much money, many people.',
      'An information → some information / a piece of information.',
      'Few vs a few: I have few friends звучит жалобно; a few friends — «есть несколько».',
    ],
    seeAlso: ['a1-some-any', 'a1-articles-plurals', 'b1-articles'],
  },
  {
    id: 'a2-modals-obligation',
    level: 'A2',
    title: 'Must / should / have to',
    gist: 'Три модальности долженствования. Must — сильное «надо» (часто внутреннее/правило). Have to — внешняя необходимость. Should — совет, не приказ.',
    form: 'must / mustn\'t + V · have to / don\'t have to + V · should / shouldn\'t + V',
    rules: [
      'Must: You must stop at red. I must remember this. Отрицание mustn\'t = запрет.',
      'Have to: I have to wear a uniform. (так требуют). Don\'t have to = не обязательно, не запрет.',
      'Should: You should see a doctor. Мягче must. Shouldn\'t — «не стоит».',
      'Must не имеет прошедшего; в прошлом — had to. Вопрос: Do you have to…? Must you…? реже.',
    ],
    examples: [
      { en: 'You mustn\'t park here.', ru: 'Здесь нельзя парковаться. (запрет)' },
      { en: 'I have to get up at six.', ru: 'Мне приходится вставать в шесть.' },
      { en: 'You don\'t have to pay now.', ru: 'Сейчас платить не обязательно.' },
      { en: 'You should take a break.', ru: 'Тебе стоит сделать перерыв.' },
      { en: 'We had to wait an hour.', ru: 'Нам пришлось ждать час.' },
    ],
    pitfalls: [
      'Mustn\'t ≠ don\'t have to. Mustn\'t — нельзя. Don\'t have to — можно не делать.',
      'I must to go → I must go. I have go → I have to go. To только у have to.',
      'You should to rest → You should rest.',
    ],
    seeAlso: ['a1-can', 'b1-modals-deduction', 'b2-had-better'],
  },
  {
    id: 'a2-first-conditional',
    level: 'A2',
    title: 'First Conditional',
    gist: 'Реальное будущее: если A случится, будет B. If + Present Simple, will + глагол. Не will в if-части.',
    form: 'If + Present Simple, will/won\'t + V · порядок частей свободный, запятая если if первым',
    rules: [
      'If it rains, we\'ll stay in. We\'ll stay in if it rains. (без запятой, когда if второй).',
      'Unless = if not: Unless you hurry, you\'ll miss it.',
      'В if-части не will: *If it will rain* — ошибка на этом уровне.',
      'Вместо will бывают can, might, imperative: If you see her, tell her. If you\'re free, we can meet.',
    ],
    examples: [
      { en: 'If I finish early, I\'ll call you.', ru: 'Если закончу рано, позвоню.' },
      { en: 'You\'ll get wet if you don\'t take a coat.', ru: 'Промокнешь, если не возьмёшь пальто.' },
      { en: 'Unless it\'s urgent, don\'t call after ten.', ru: 'Если это не срочно, не звони после десяти.' },
      { en: 'If you need help, just ask.', ru: 'Если нужна помощь — просто скажи.' },
      { en: 'We might cancel if the train is late.', ru: 'Можем отменить, если поезд опоздает.' },
    ],
    pitfalls: [
      'If I will see him… → If I see him…',
      'If I would… на реальное будущее — это уже second conditional (B1).',
      'When vs if: when — «когда точно случится»; if — условие.',
    ],
    seeAlso: ['a2-will-going-to', 'b1-second-conditional', 'b2-third-mixed-conditionals'],
  },
  {
    id: 'a2-word-order',
    level: 'A2',
    title: 'Порядок слов и наречия частоты',
    gist: 'Английский держит SVO: подлежащее — глагол — дополнение. Наречия частоты (always, often, never) живут перед смысловым глаголом и после be.',
    form: 'подлежащее + (наречие) + глагол + дополнение · be + наречие · never / hardly ever почти не в конце',
    rules: [
      'I often eat late. She is always late. He can never remember. (после первого вспомогательного/модального).',
      'Обычный порядок обстоятельств: как — где — когда: She sang well at the concert yesterday.',
      'Вопрос: вспомогательный + подлежащее + смысловой: Where do you live? Не *Where you live?*',
      'Never / hardly ever = отрицательный смысл; второй not не нужен.',
    ],
    examples: [
      { en: 'I usually get up at seven.', ru: 'Обычно я встаю в семь.' },
      { en: 'They are never at home.', ru: 'Их никогда нет дома.' },
      { en: 'We don\'t often eat out.', ru: 'Мы нечасто едим вне дома.' },
      { en: 'She can barely hear you.', ru: 'Она тебя едва слышит.' },
      { en: 'I saw him at the station this morning.', ru: 'Я видел его на вокзале сегодня утром.' },
    ],
    pitfalls: [
      'I eat often pizza → I often eat pizza. Наречие не между глаголом и дополнением без нужды.',
      'Always I… в начале звучит тяжело; обычное место — перед глаголом.',
      'I don\'t never → I never / I don\'t ever.',
    ],
    seeAlso: ['a1-present-simple', 'a1-to-be', 'a2-gerund-infinitive'],
  },
  {
    id: 'a2-gerund-infinitive',
    level: 'A2',
    title: 'Gerund vs infinitive: база',
    gist: 'После одних глаголов — V-ing, после других — to + V. На A2 достаточно короткого списка, не всех 200 пар.',
    form: 'like/love/enjoy/finish/avoid + V-ing · want/need/decide/plan/hope + to V · would like + to V',
    rules: [
      'Gerund как подлежащее: Swimming is fun. После предлога всегда -ing: I\'m good at drawing. Thank you for coming.',
      'Want, need, decide, forget (намерение), hope, promise, refuse — to-infinitive.',
      'Enjoy, finish, mind, keep, avoid, suggest — V-ing. I enjoy to swim — ошибка.',
      'Like / love / hate — часто оба варианта; would like только to.',
    ],
    examples: [
      { en: 'I enjoy cooking.', ru: 'Мне нравится готовить.' },
      { en: 'She wants to leave.', ru: 'Она хочет уйти.' },
      { en: 'We decided to wait.', ru: 'Мы решили подождать.' },
      { en: 'He\'s interested in learning Spanish.', ru: 'Ему интересно учить испанский.' },
      { en: 'I\'d like to book a table.', ru: 'Я хотел бы забронировать столик.' },
    ],
    pitfalls: [
      'I want going → I want to go.',
      'I enjoy to read → I enjoy reading.',
      'Look forward to meet you → look forward to meeting (to здесь предлог).',
    ],
    seeAlso: ['a1-present-simple', 'b1-gerund-infinitive', 'b2-remember-try'],
  },
  {
    id: 'a2-relative-basic',
    level: 'A2',
    title: 'Who / which / that',
    gist: 'Простые относительные: кто, что, который. Сжимают два предложения в одно: The man who called is my boss.',
    form: 'who — люди · which — вещи · that — и люди, и вещи в defining-придаточных',
    rules: [
      'The woman who lives next door. The book which/that I bought. На A2 that часто универсален.',
      'Where — места: the café where we met. Whose — чей: the man whose car was stolen (уже верх A2 / низ B1).',
      'Если who/which/that — дополнение, в разговоре его часто опускают: the film I saw.',
      'Не ставь what вместо which/that: the thing what I need → the thing that I need.',
    ],
    examples: [
      { en: 'That\'s the person who helped me.', ru: 'Это человек, который мне помог.' },
      { en: 'I need a bag that is light.', ru: 'Мне нужна сумка, которая лёгкая.' },
      { en: 'This is the house where I grew up.', ru: 'Это дом, где я вырос.' },
      { en: 'The shoes I bought are too small.', ru: 'Туфли, которые я купил, малы. (that опущено)' },
      { en: 'She works for a company which makes apps.', ru: 'Она работает в компании, которая делает приложения.' },
    ],
    pitfalls: [
      'The man which… для людей лучше who.',
      'The film what I saw → the film that/which I saw / the film I saw.',
      'Who you talking to? в придаточном: the person who you\'re talking to / …you\'re talking to.',
    ],
    seeAlso: ['b1-defining-relative', 'b2-non-defining-relative', 'a1-pronouns'],
  },
  {
    id: 'a2-passive',
    level: 'A2',
    title: 'Passive: Present и Past Simple',
    gist: 'Залог, когда важен объект, а не «кто сделал»: English is spoken here. Форма: be + V3.',
    form: 'Present: am/is/are + V3 · Past: was/were + V3 · by + деятель (необязательно)',
    rules: [
      'The emails are sent every morning. The window was broken yesterday.',
      'Деятель: The cake was made by Tom. Если деятель неважен — by опускают.',
      'Только переходные глаголы: *is happened неверно — happen непереходный, нужен The accident happened.',
      'Отрицание и вопрос через be: Was it painted? It isn\'t included.',
    ],
    examples: [
      { en: 'Spanish is spoken in many countries.', ru: 'На испанском говорят во многих странах.' },
      { en: 'The museum was closed last Monday.', ru: 'Музей был закрыт в прошлый понедельник.' },
      { en: 'My bike was stolen.', ru: 'Мой велосипед украли.' },
      { en: 'Are the rooms cleaned every day?', ru: 'Комнаты убирают каждый день?' },
      { en: 'The film was directed by Nolan.', ru: 'Фильм снял Нолан.' },
    ],
    pitfalls: [
      'The letter sent yesterday → The letter was sent yesterday.',
      'It was happened → It happened.',
      'By who? → Who was it written by? / By whom… (формально).',
    ],
    seeAlso: ['a1-to-be', 'b1-passive-more', 'b2-passive-causative'],
  },
]
