import type { GrammarLesson } from '../types'

export const B1_LESSONS: GrammarLesson[] = [
  {
    id: 'b1-pp-vs-past',
    level: 'B1',
    title: 'Present Perfect vs Past Simple',
    gist: 'Главный развилка B1. Past Simple — закрытый момент в прошлом. Present Perfect — прошлое без рамки или с эффектом сейчас.',
    form: 'Past Simple: V2 / did + V1 + маркер времени · Present Perfect: have/has + V3 без «вчера»',
    rules: [
      'Есть when / yesterday / last / ago / in 2019 — почти всегда Past Simple: I saw her yesterday.',
      'Нет точки во времени, важен опыт или итог: I\'ve seen that film. (когда — неважно). She\'s broken her arm. (гипс сейчас).',
      'How long + for/since с незакрытым сроком: I\'ve lived here since 2018. (и живу). I lived there in 2015. (уже не живу).',
      'Just/already/yet — Perfect. Когда назвал час/дату — Simple.',
    ],
    examples: [
      { en: 'I lost my keys yesterday.', ru: 'Вчера я потерял ключи. (когда известно)' },
      { en: 'I\'ve lost my keys.', ru: 'Я потерял ключи. (их нет сейчас)' },
      { en: 'Did you go to Paris in 2019?', ru: 'Ты ездил в Париж в 2019?' },
      { en: 'Have you ever been to Paris?', ru: 'Ты когда-нибудь был в Париже?' },
      { en: 'She worked there for two years.', ru: 'Она там проработала два года. (закончилось)' },
      { en: 'She has worked there for two years.', ru: 'Она там работает уже два года.' },
    ],
    pitfalls: [
      'I\'ve seen him last week → I saw him last week.',
      'When have you arrived? → When did you arrive? When требует Simple.',
      'I am here since Monday → I\'ve been here since Monday.',
    ],
    seeAlso: ['a2-present-perfect', 'a2-past-simple-irregular', 'b1-pp-continuous'],
  },
  {
    id: 'b1-pp-continuous',
    level: 'B1',
    title: 'Present Perfect Continuous',
    gist: 'Have been + V-ing — действие тянется к настоящему, часто с акцентом на процесс и how long, а не на «уже готовый результат».',
    form: 'have/has + been + V-ing · how long / for / since / all day',
    rules: [
      'I\'ve been waiting for an hour. (процесс до сейчас). I\'ve waited — тоже можно, но Continuous сильнее рисует длительность.',
      'Видимый эффект процесса: You\'re sweaty — have you been running?',
      'Глаголы состояния: I\'ve known her for years. Не *I\'ve been knowing.',
      'Сколько сделано / сколько раз — обычно Simple: I\'ve read three chapters. Не Continuous.',
    ],
    examples: [
      { en: 'I\'ve been learning English since May.', ru: 'Я учу английский с мая.' },
      { en: 'It\'s been raining all morning.', ru: 'Дождь идёт всё утро.' },
      { en: 'Have you been crying?', ru: 'Ты плакал?' },
      { en: 'She hasn\'t been sleeping well.', ru: 'Она плохо спит в последнее время.' },
      { en: 'I\'ve been working here for six months.', ru: 'Я здесь работаю полгода.' },
    ],
    pitfalls: [
      'I\'m living here for 3 years → I\'ve been living / I\'ve lived here for 3 years. Present Continuous не несёт «уже сколько».',
      'I\'ve been knowing him → I\'ve known him.',
      'I\'ve been reading 40 pages — если важен итог, лучше I\'ve read 40 pages.',
    ],
    seeAlso: ['b1-pp-vs-past', 'a2-present-perfect', 'a1-present-continuous'],
  },
  {
    id: 'b1-past-perfect',
    level: 'B1',
    title: 'Past Perfect',
    gist: 'Had + V3 — «ещё раньше», чем другое прошлое. Нужен, когда в рассказе два прошлых слоя.',
    form: 'had + V3 · hadn\'t · Had + подлежащее + V3? · часто с before / after / by the time / already',
    rules: [
      'When I arrived, the film had started. (фильм раньше приезда).',
      'Без второго прошлого якоря had не обязателен: I had breakfast and left — два простых Past Simple подряд ок, если порядок очевиден.',
      'Reported speech: She said she had already eaten. (ещё раньше момента речи в прошлом).',
      'If в третьем типе: If I had known… — отдельно на B2.',
    ],
    examples: [
      { en: 'The train had left when we got there.', ru: 'Поезд уже ушёл, когда мы добрались.' },
      { en: 'I didn\'t eat because I had already had lunch.', ru: 'Я не ел: я уже пообедал.' },
      { en: 'By the time she called, I had gone out.', ru: 'К тому моменту, как она позвонила, я уже вышел.' },
      { en: 'He realised he had forgotten the keys.', ru: 'Он понял, что забыл ключи.' },
      { en: 'We\'d never met before that day.', ru: 'Мы не встречались до того дня.' },
    ],
    pitfalls: [
      'When I was a child I had lived… для биографии чаще I lived. Past Perfect не «любое давно».',
      'I had went → I had gone.',
      'Ставить had в каждое предложение рассказа — перегруз. Нужен только сдвиг «ещё раньше».',
    ],
    seeAlso: ['a2-past-continuous', 'b1-reported-speech', 'b2-third-mixed-conditionals'],
  },
  {
    id: 'b1-future-forms',
    level: 'B1',
    title: 'Будущее: will, going to, Present Continuous',
    gist: 'Три рабочих будущих. Present Continuous — договорённость в календаре. Going to — намерение. Will — спонтанность, обещание, мнение.',
    form: 'I\'m meeting her at 6 · I\'m going to look for a job · I\'ll text you',
    rules: [
      'Present Continuous + будущее время: I\'m flying tomorrow. (билет есть). Не для голых предсказаний: *It\'s raining tomorrow.',
      'Going to — план без обязательной «ячейки в календаре»: I\'m going to cook more.',
      'Will — I think / probably / I\'m sure; обещания; решение сейчас.',
      'Timetables остаются Present Simple: The bus leaves at 9. (расписание).',
    ],
    examples: [
      { en: 'I\'m seeing the dentist on Monday.', ru: 'В понедельник иду к стоматологу. (запись)' },
      { en: 'I\'m going to apply next week.', ru: 'На следующей неделе подам заявку. (намерение)' },
      { en: 'I\'ll see what I can do.', ru: 'Посмотрю, что смогу сделать.' },
      { en: 'The course starts on 3 March.', ru: 'Курс начинается 3 марта. (расписание)' },
      { en: 'Look at the time — we\'re going to be late.', ru: 'Смотри сколько времени — мы опоздаем.' },
    ],
    pitfalls: [
      'I will go to the doctor tomorrow при уже записанном приёме — лучше I\'m going / I\'m seeing.',
      'It will raining → It will rain / It\'s going to rain.',
      'Present Simple для личного плана: I fly tomorrow звучит как расписание, не как «я решил».',
    ],
    seeAlso: ['a2-will-going-to', 'a1-going-to', 'b2-future-perfect'],
  },
  {
    id: 'b1-second-conditional',
    level: 'B1',
    title: 'Second Conditional',
    gist: 'Нереальное настоящее/будущее: если бы сейчас было иначе. If + Past Simple, would + глагол. Вежливость: If I were you…',
    form: 'If + Past Simple, would/wouldn\'t + V · If I were (не was в советах) · could/might вместо would',
    rules: [
      'If I had more time, I\'d learn the piano. (сейчас времени нет).',
      'Прошедшее здесь не про прошлое, а «дистанция от реальности».',
      'If I were you, I\'d apologise. Were для всех лиц в этом шаблоне — норма.',
      'Would не ставят в if-части: *If I would have time.',
    ],
    examples: [
      { en: 'If I lived closer, I\'d walk to work.', ru: 'Если бы я жил ближе, ходил бы пешком.' },
      { en: 'What would you do if you won the lottery?', ru: 'Что бы ты сделал, если бы выиграл лотерею?' },
      { en: 'If I were you, I wouldn\'t wait.', ru: 'На твоём месте я бы не ждал.' },
      { en: 'We could travel more if we earned more.', ru: 'Могли бы больше путешествовать, если бы больше зарабатывали.' },
      { en: 'If it wasn\'t / weren\'t so late, I\'d stay.', ru: 'Если бы не было так поздно, я бы остался.' },
    ],
    pitfalls: [
      'If I would be rich… → If I were/was rich…',
      'Путать с first: реальное «если завтра дождь» — first; мечта/маловероятное — second.',
      'If I would have known — это ломаный third; правильный на B2: If I had known.',
    ],
    seeAlso: ['a2-first-conditional', 'b1-wish', 'b2-third-mixed-conditionals'],
  },
  {
    id: 'b1-reported-speech',
    level: 'B1',
    title: 'Reported speech: утверждения',
    gist: 'Косвенная речь: сдвиг времени, если reporting глагол в прошлом. She said she was tired. Местоимения и указатели времени тоже едут.',
    form: 'said (that) + сдвиг · told + объект + (that) · Present → Past · will → would · Past Simple / Present Perfect → Past Perfect',
    rules: [
      'She said, «I\'m busy» → She said she was busy. He told me he had already left.',
      'Say без объекта: she said (that)… Tell всегда с объектом: she told me… Не *she said me*.',
      'Сдвиг не нужен, если факт всё ещё верен: He said the Earth is round. Или reporting в Present: She says she\'s tired.',
      'Yesterday → the day before; tomorrow → the next day; here → there; this → that — по смыслу, не механически всегда.',
    ],
    examples: [
      { en: '«I work here.» → She said she worked there.', ru: 'Она сказала, что работает там.' },
      { en: '«I\'ll call you.» → He said he would call me.', ru: 'Он сказал, что позвонит.' },
      { en: '«We\'ve met.» → They said they had met.', ru: 'Они сказали, что уже встречались.' },
      { en: 'She told us the shop was closed.', ru: 'Она сказала нам, что магазин закрыт.' },
      { en: 'He says he\'s on his way. (без сдвига)', ru: 'Он говорит, что уже едет.' },
    ],
    pitfalls: [
      'She said me that… → She told me that… / She said that…',
      'He said he will come при said в прошлом → he would come.',
      'Каждый раз насильно сдвигать вечные истины не нужно.',
    ],
    seeAlso: ['b1-past-perfect', 'b2-reported-questions', 'a2-will-going-to'],
  },
  {
    id: 'b1-passive-more',
    level: 'B1',
    title: 'Passive шире Present/Past Simple',
    gist: 'Be в нужном времени + V3. Present Perfect, will, модальные: The work has been done. It will be delivered. It can be fixed.',
    form: 'have/has been + V3 · will be + V3 · modal + be + V3 · being + V3 (Continuous, реже)',
    rules: [
      'The issue has been solved. A new office is being built. (прямо сейчас строят).',
      'It must be finished today. The form should be signed.',
      'Два объекта: I was given a key. / A key was given to me. Give, send, show, tell — часто «мне дали».',
      'Get-passive разговорный: I got stuck. He got fired. Не в самом формальном стиле.',
    ],
    examples: [
      { en: 'My car has been repaired.', ru: 'Машину починили. (уже)' },
      { en: 'The results will be announced tomorrow.', ru: 'Результаты объявят завтра.' },
      { en: 'This can be done later.', ru: 'Это можно сделать позже.' },
      { en: 'I was offered a better role.', ru: 'Мне предложили роль получше.' },
      { en: 'The road is being repaired.', ru: 'Дорогу ремонтируют.' },
    ],
    pitfalls: [
      'It has been happen → It has happened / It has been done (если есть объект).',
      'The letter will send → The letter will be sent.',
      'I was said the news → I was told the news. Say не берёт такой пассив с «мне сказали».',
    ],
    seeAlso: ['a2-passive', 'b2-passive-causative', 'b1-modals-deduction'],
  },
  {
    id: 'b1-modals-deduction',
    level: 'B1',
    title: 'Might / must / can\'t: предположение',
    gist: 'Не обязанность, а оценка вероятности сейчас. Must — почти уверен. Might/may/could — возможно. Can\'t — «не может быть».',
    form: 'must + V · might/may/could + V · can\'t + V · не can в значении «вероятно, что да»',
    rules: [
      'The lights are on — they must be at home. She might be late. That can\'t be true.',
      'Mustn\'t здесь не «вероятно, что нет» — это запрет. Для «точно не» бери can\'t.',
      'Could в предположении ≈ might. Can в утверждении «наверное» почти не работает: *He can be at home так не говорят.',
      'Про прошлое — must have / might have на B2.',
    ],
    examples: [
      { en: 'He\'s not answering. He must be busy.', ru: 'Не берёт трубку. Наверняка занят.' },
      { en: 'She might not know yet.', ru: 'Она, возможно, ещё не знает.' },
      { en: 'That can\'t be her car — it\'s the wrong colour.', ru: 'Это не может быть её машина.' },
      { en: 'They could be stuck in traffic.', ru: 'Они, может, стоят в пробке.' },
      { en: 'You must be joking.', ru: 'Ты, наверное, шутишь.' },
    ],
    pitfalls: [
      'He can be tired в смысле «наверное устал» → He might/must be tired.',
      'Mustn\'t be the answer в смысле «вряд ли» → can\'t be.',
      'Путать must «надо» и must «наверняка»: контекст — обязанность vs логика.',
    ],
    seeAlso: ['a2-modals-obligation', 'b2-modals-perfect', 'a1-can'],
  },
  {
    id: 'b1-defining-relative',
    level: 'B1',
    title: 'Defining relative clauses',
    gist: 'Придаточное, без которого не ясно, о ком речь. Без запятых. Who/which/that; whom редко; whose; where/when.',
    form: 'the person who/that… · the thing which/that… · the place where… · whose + сущ. · опущение that/who в роли дополнения',
    rules: [
      'The students who passed can leave. (какие именно студенты — только сдавшие).',
      'Предлог в конце естественен: the company I work for. Формально: for which I work.',
      'That не ставят после запятой и не используют в non-defining (это B2).',
      'What ≠ that: That\'s what I meant. (то, что). The book what I read — ошибка.',
    ],
    examples: [
      { en: 'The woman who called you is my aunt.', ru: 'Женщина, которая тебе звонила, — моя тётя.' },
      { en: 'This is the only key that works.', ru: 'Это единственный ключ, который подходит.' },
      { en: 'The people we met were kind.', ru: 'Люди, которых мы встретили, были добрыми.' },
      { en: 'I need a place where I can focus.', ru: 'Мне нужно место, где я могу сосредоточиться.' },
      { en: 'She\'s the designer whose work I follow.', ru: 'Это дизайнер, за чьей работой я слежу.' },
    ],
    pitfalls: [
      'Запятые как в русском «мой брат, который…» когда брат один — это уже non-defining, не defining.',
      'The man, that I saw — that с запятыми не сочетается.',
      'Who в роли дополнения с предлогом: the person with who I spoke → with whom / who I spoke with / that I spoke with.',
    ],
    seeAlso: ['a2-relative-basic', 'b2-non-defining-relative', 'b2-participle-clauses'],
  },
  {
    id: 'b1-gerund-infinitive',
    level: 'B1',
    title: 'Gerund / infinitive: расширенный список',
    gist: 'На B1 добавляются глаголы с фиксированным выбором и конструкции verb + object + to. Пары с разным смыслом (remember, stop) — на B2.',
    form: 'admit/avoid/consider/deny/fancy/finish/miss/practise/risk/suggest + V-ing · agree/afford/arrange/choose/deserve/expect/fail/manage/offer/prepare/pretend/refuse/seem + to V',
    rules: [
      'Suggest + -ing или suggest that + clause. Не *suggest to go. Let me suggest going earlier.',
      'Make / let + object + голый инфинитив: She made me wait. Let him speak. Help — to или голый.',
      'Advise / allow / permit + object + to: They allowed us to leave. Без объекта: They allowed parking? лучше They allowed us to park / parking was allowed.',
      'Used to + V (привычка в прошлом) ≠ be used to + -ing — отдельная тема.',
    ],
    examples: [
      { en: 'She suggested waiting.', ru: 'Она предложила подождать.' },
      { en: 'He managed to finish on time.', ru: 'Он умудрился закончить вовремя.' },
      { en: 'They made us rewrite it.', ru: 'Нас заставили переписать.' },
      { en: 'I can\'t afford to rent a larger flat.', ru: 'Я не могу позволить себе снимать квартиру побольше.' },
      { en: 'We expect the results to arrive today.', ru: 'Мы ждём, что результаты придут сегодня.' },
    ],
    pitfalls: [
      'I suggest to go → I suggest going / I suggest that we go.',
      'She made me to wait → She made me wait.',
      'I look forward to hear → I look forward to hearing.',
    ],
    seeAlso: ['a2-gerund-infinitive', 'b1-used-to', 'b2-remember-try'],
  },
  {
    id: 'b1-wish',
    level: 'B1',
    title: 'Wish + past',
    gist: 'I wish + Past Simple — жаль, что сейчас не так. I wish + would — раздражение / хочу, чтобы другой изменил поведение.',
    form: 'I wish + Past Simple (настоящее) · I wish + would + V (чужое поведение) · If only = усиленное wish',
    rules: [
      'I wish I knew. I wish I had a car. Это не прошедшее событие, а нереальное сейчас (как second conditional).',
      'I wish you would stop tapping. Не про себя: *I wish I would… обычно нет.',
      'I wish I could… — жаль, что не умею / не могу.',
      'Прошедшее сожаление I wish I had + V3 — B2 (вместе с third conditional).',
    ],
    examples: [
      { en: 'I wish I spoke French.', ru: 'Жаль, что я не говорю по-французски.' },
      { en: 'I wish it wasn\'t / weren\'t raining.', ru: 'Жаль, что идёт дождь.' },
      { en: 'I wish you would listen.', ru: 'Послушал бы ты уже.' },
      { en: 'If only we lived closer.', ru: 'Если бы мы жили ближе.' },
      { en: 'I wish I could stay longer.', ru: 'Жаль, что не могу остаться.' },
    ],
    pitfalls: [
      'I wish I know → I wish I knew.',
      'I wish I would have a car → I wish I had a car.',
      'I hope I knew — hope про реальное будущее: I hope I\'ll know soon.',
    ],
    seeAlso: ['b1-second-conditional', 'b2-wish-if-only', 'b2-had-better'],
  },
  {
    id: 'b1-articles',
    level: 'B1',
    title: 'Артикли: рабочая система',
    gist: 'A — впервые / один из класса. The — известный слушателю, единственный в контексте, уникальные. Zero — обобщения во множественном и неисчисляемые «вообще».',
    form: 'a/an + ед. исчисл. · the + конкретное · Ø + мн. / неисчисл. в общем смысле',
    rules: [
      'I bought a laptop. The laptop is slow. (уже тот самый).',
      'The sun, the government, the same, the first, the wrong/right. Superlatives: the best.',
      'Life is short. I like music. Dogs make good pets. — без the, если «вообще». The life of a surgeon — конкретный срез.',
      'Institutions: at school / in hospital (BrE, как пациент) vs at the school (здание, не ученик).',
    ],
    examples: [
      { en: 'She is a lawyer.', ru: 'Она юрист.' },
      { en: 'Could you pass the salt?', ru: 'Передай соль. (на столе, известна)' },
      { en: 'I love coffee.', ru: 'Я люблю кофе. (вообще)' },
      { en: 'The coffee here is excellent.', ru: 'Здешний кофе отличный.' },
      { en: 'He went to university in 2018.', ru: 'Он поступил в университет в 2018. (как студент)' },
    ],
    pitfalls: [
      'I go to the school every day как ученик → I go to school.',
      'The life is beautiful → Life is beautiful.',
      'She is the doctor если профессия впервые → She is a doctor. The doctor — «тот врач», о котором уже речь.',
    ],
    seeAlso: ['a1-articles-plurals', 'a2-countable', 'a1-prepositions'],
  },
  {
    id: 'b1-although-despite',
    level: 'B1',
    title: 'Although / despite / however',
    gist: 'Уступка: «хотя / несмотря на / однако». Разная грамматика: although + предложение, despite + существительное/-ing, however — наречие с точкой или точкой с запятой.',
    form: 'although / even though + clause · despite / in spite of + noun / -ing · however + новое предложение',
    rules: [
      'Although it was late, we stayed. Even though сильнее although.',
      'Despite the rain, we went out. Despite being tired… Не *despite it was late — нужен despite the fact that или although.',
      'However стоит между предложениями: It was late. However, we stayed. Запятая после however в начале.',
      'But — сочинительный, проще. However формальнее. Whereas — контраст двух фактов.',
    ],
    examples: [
      { en: 'Although I was tired, I finished the task.', ru: 'Хотя я устал, я закончил задачу.' },
      { en: 'Despite the noise, she slept.', ru: 'Несмотря на шум, она спала.' },
      { en: 'In spite of feeling ill, he came.', ru: 'Несмотря на то что ему было плохо, он пришёл.' },
      { en: 'The plan looked good. However, it failed.', ru: 'План выглядел хорошо. Однако он провалился.' },
      { en: 'Even though we hurried, we missed it.', ru: 'Даже несмотря на то что мы спешили, мы опоздали.' },
    ],
    pitfalls: [
      'Despite it was raining → Although it was raining / Despite the rain / Despite the fact that it was raining.',
      'Although the rain → Although it was raining. Although хочет подлежащее и глагол.',
      'However I tried, … в значении «как бы ни» — это however другой, лучше Even though I tried / However hard I tried (inversion-ish, выше).',
    ],
    seeAlso: ['b2-discourse', 'a2-word-order', 'b1-defining-relative'],
  },
  {
    id: 'b1-used-to',
    level: 'B1',
    title: 'Used to vs be used to / get used to',
    gist: 'Три разных used. Used to + V — бывало в прошлом, сейчас нет. Be used to + -ing/noun — привычен. Get used to — привыкаешь.',
    form: 'used to + V · didn\'t use to + V · be used to + -ing/noun · get used to + -ing/noun',
    rules: [
      'I used to smoke. I didn\'t use to like olives. Did you use to…? (без d в вопросе/отрицании с did).',
      'I\'m used to getting up early. (мне это привычно сейчас). Не *I\'m used to get.',
      'You\'ll get used to the noise. Get used to = процесс привыкания.',
      'Would + V тоже «бывало», но только повторяющиеся действия, не состояния: We\'d go to the lake. Не *I would be shy как used to be shy.',
    ],
    examples: [
      { en: 'She used to live in Rome.', ru: 'Она раньше жила в Риме.' },
      { en: 'I didn\'t use to drink coffee.', ru: 'Раньше я не пил кофе.' },
      { en: 'I\'m used to the traffic now.', ru: 'Я уже привык к пробкам.' },
      { en: 'He isn\'t used to working nights.', ru: 'Он не привык работать по ночам.' },
      { en: 'I\'m getting used to the new keyboard.', ru: 'Я привыкаю к новой клавиатуре.' },
    ],
    pitfalls: [
      'I am used to live → I used to live (прошлое) или I\'m used to living (привычка сейчас).',
      'I used to living → I used to live.',
      'Did you used to… → Did you use to…',
    ],
    seeAlso: ['a1-past-simple', 'b1-gerund-infinitive', 'b1-second-conditional'],
  },
]
