import type { GrammarLesson } from '../types'

export const B2_LESSONS: GrammarLesson[] = [
  {
    id: 'b2-third-mixed-conditionals',
    level: 'B2',
    title: 'Third и mixed conditionals',
    gist: 'Third — нереальное прошлое: If I had + V3, I would have + V3. Mixed — прошлое условие и нынешний результат (или наоборот).',
    form: 'If + Past Perfect, would have + V3 · mixed: If + Past Perfect, would + V · If + Past Simple, would have + V3',
    rules: [
      'If I had left earlier, I would have caught the train. (не поймал — поезд ушёл).',
      'Mixed 1: If I had studied medicine, I would be a doctor now. (прошлое → настоящее).',
      'Mixed 2: If I were more careful, I wouldn\'t have made that mistake. (характер сейчас → прошлое событие).',
      'Could have / might have вместо would have: If you\'d asked, I could have helped.',
    ],
    examples: [
      { en: 'If she had called, I would have picked up.', ru: 'Если бы она позвонила, я бы взял трубку.' },
      { en: 'I wouldn\'t have met her if I hadn\'t taken that job.', ru: 'Я бы с ней не встретился, если бы не взял ту работу.' },
      { en: 'If I had slept more, I wouldn\'t be so tired now.', ru: 'Если бы я больше поспал, сейчас не был бы таким уставшим.' },
      { en: 'If he were honest, he would have told us.', ru: 'Если бы он был честным, он бы нам сказал.' },
      { en: 'If you\'d listened, you might have understood.', ru: 'Если бы ты слушал, возможно, понял бы.' },
    ],
    pitfalls: [
      'If I would have known → If I had known. Would не в if-части.',
      'If I knew, I would have helped — смешанный тип ок, только если «знал бы (характер/сейчас)». Для чистого прошлого — If I had known.',
      'I would had gone → I would have gone.',
    ],
    seeAlso: ['b1-second-conditional', 'b1-past-perfect', 'b2-wish-if-only'],
  },
  {
    id: 'b2-wish-if-only',
    level: 'B2',
    title: 'Wish / if only / I\'d rather',
    gist: 'Сожаление о прошлом: wish + Past Perfect. If only — то же, сильнее. I\'d rather + Past — «лучше бы ты…» про настоящее.',
    form: 'I wish / If only + Past Perfect (прошлое) · I\'d rather + Past Simple (сейчас, чужое действие) · I\'d rather + V (своё предпочтение)',
    rules: [
      'I wish I hadn\'t said that. If only we\'d left sooner.',
      'I\'d rather you didn\'t smoke here. (вежливый запрет). I\'d rather stay in. (сам).',
      'It\'s time you went to bed. Past Simple после it\'s time — «уже пора», не прошлое событие.',
      'Wish + would по-прежнему про чужое раздражающее поведение, не про прошлое.',
    ],
    examples: [
      { en: 'I wish I had taken the job.', ru: 'Жаль, что я не взял ту работу.' },
      { en: 'If only I had checked the address.', ru: 'Если бы я только проверил адрес.' },
      { en: 'I\'d rather you called tomorrow.', ru: 'Лучше позвони завтра.' },
      { en: 'It\'s time we left.', ru: 'Нам уже пора уходить.' },
      { en: 'I wish you wouldn\'t interrupt.', ru: 'Перестань, пожалуйста, перебивать.' },
    ],
    pitfalls: [
      'I wish I would have gone → I wish I had gone.',
      'I\'d rather you to go → I\'d rather you went / I\'d rather you didn\'t go.',
      'It\'s time to go — нормально про себя. It\'s time you go → It\'s time you went.',
    ],
    seeAlso: ['b1-wish', 'b2-third-mixed-conditionals', 'b2-had-better'],
  },
  {
    id: 'b2-reported-questions',
    level: 'B2',
    title: 'Косвенные вопросы и reporting verbs',
    gist: 'В косвенном вопросе порядок как в утверждении, без do. Ask if/whether; ask + wh. Reporting verbs несут смысл: refuse, suggest, warn.',
    form: 'asked if/whether + clause · asked + wh-слово + clause (без do) · verb + to V / verb + -ing / verb + that — по глаголу',
    rules: [
      '«Where do you live?» → He asked where I lived. Не *where did I live и не *where do I live после asked в прошлом (со сдвигом).',
      'Yes/no: She asked if I was ready. Whether — чуть формальнее, обязателен перед or not в ряде случаев.',
      'Suggest + -ing / that: He suggested leaving. He suggested (that) we leave. Не *suggested to leave.',
      'Refuse / offer / promise + to: She refused to sign. Warn + object + that / against -ing. Admit + -ing / that.',
    ],
    examples: [
      { en: 'She asked me what the time was.', ru: 'Она спросила, который час.' },
      { en: 'They asked if we had eaten.', ru: 'Они спросили, ели ли мы.' },
      { en: 'He wanted to know how long I had been waiting.', ru: 'Он хотел знать, как давно я жду.' },
      { en: 'She refused to comment.', ru: 'Она отказалась комментировать.' },
      { en: 'He suggested that we postpone the call.', ru: 'Он предложил перенести звонок.' },
    ],
    pitfalls: [
      'He asked me where did I go → He asked me where I went / had gone.',
      'She asked me to where I live — лишний to.',
      'He said me to go → He told me to go. Said не берёт объект так.',
    ],
    seeAlso: ['b1-reported-speech', 'b1-past-perfect', 'b1-gerund-infinitive'],
  },
  {
    id: 'b2-passive-causative',
    level: 'B2',
    title: 'Passive и have something done',
    gist: 'Causative: have/get + object + V3 — «мне это сделали / я заказал услугу». Не «я сам сделал».',
    form: 'have/get + объект + V3 · get чуть разговорнее · need + V-ing (BrE) ≈ needs to be done',
    rules: [
      'I\'m having my hair cut tomorrow. We had the roof repaired. (мастера).',
      'Get something done — то же + оттенок «удалось / устроил»: I finally got the printer fixed.',
      'Have + object + V (голый) — «заставить»: I\'ll have him call you. Это другой have, не causative с V3.',
      'The car needs washing / needs to be washed.',
    ],
    examples: [
      { en: 'I need to have this document translated.', ru: 'Мне нужно перевести этот документ. (не сам)' },
      { en: 'She\'s having her apartment painted.', ru: 'Ей красят квартиру.' },
      { en: 'We got the photos printed.', ru: 'Мы напечатали фото (в сервисе).' },
      { en: 'He had his wallet stolen.', ru: 'У него украли кошелёк. (нежелательный causative)' },
      { en: 'The lock needs replacing.', ru: 'Замок надо заменить.' },
    ],
    pitfalls: [
      'I cut my hair вчера в салоне — по-английски чаще I had my hair cut, иначе звучит «сам ножницами».',
      'I have done my car repair → I had my car repaired / I repaired my car (сам).',
      'Get stolen vs have stolen: I had my phone stolen привычнее для «у меня украли».',
    ],
    seeAlso: ['b1-passive-more', 'a2-passive', 'b1-gerund-infinitive'],
  },
  {
    id: 'b2-modals-perfect',
    level: 'B2',
    title: 'Must have / might have / should have',
    gist: 'Модальный + have + V3 — оценка прошлого. Must have — логический вывод. Might/may/could have — возможно, было. Should have — надо было, а не сделал. Can\'t have — не могло быть.',
    form: 'must/might/may/could/can\'t/should/ought to + have + V3',
    rules: [
      'He\'s late — he must have missed the bus. The lights were off — they can\'t have been at home.',
      'Should have: You should have told me. Упрёк или сожаление. Shouldn\'t have — зря сделал.',
      'Needn\'t have + V3 — сделал, хотя не было нужно. Didn\'t need to — не было нужно (и часто не делал).',
      'Could have — упущенная возможность: You could have called.',
    ],
    examples: [
      { en: 'She must have forgotten.', ru: 'Она, должно быть, забыла.' },
      { en: 'I might have left the keys at work.', ru: 'Я, возможно, оставил ключи на работе.' },
      { en: 'You should have asked first.', ru: 'Надо было сначала спросить.' },
      { en: 'He can\'t have done it alone.', ru: 'Он не мог сделать это один.' },
      { en: 'You needn\'t have bought more milk. We still had some.', ru: 'Зря купил ещё молоко — ещё было.' },
    ],
    pitfalls: [
      'He must has gone → He must have gone.',
      'Mustn\'t have в смысле «вряд ли» — лучше can\'t have. Mustn\'t have редкая и другая.',
      'I didn\'t need to go и I needn\'t have gone — разный факт: ходил или нет.',
    ],
    seeAlso: ['b1-modals-deduction', 'a2-modals-obligation', 'b2-third-mixed-conditionals'],
  },
  {
    id: 'b2-future-perfect',
    level: 'B2',
    title: 'Future Continuous и Future Perfect',
    gist: 'Не обязательны в каждой реплике, но на B2 их узнают и собирают. Continuous — действие в точке будущего. Perfect — «уже будет сделано к сроку».',
    form: 'will be + V-ing · will have + V3 · going to be + V-ing реже',
    rules: [
      'This time tomorrow I\'ll be sitting on the train. Вежливый вопрос о планах: Will you be using the printer?',
      'By Friday I\'ll have finished the draft. К моменту в будущем итог уже есть.',
      'Future Perfect Continuous (will have been + -ing) — редкий; достаточно узнавать: I\'ll have been working here for a year in May.',
      'Для личного календаря по-прежнему сильны Present Continuous и going to; эти формы — аспект, не замена плану.',
    ],
    examples: [
      { en: 'Don\'t call at 8 — I\'ll be having dinner.', ru: 'Не звони в восемь: я буду ужинать.' },
      { en: 'Will you be staying long?', ru: 'Ты надолго? (вежливо про планы)' },
      { en: 'By the time you arrive, I\'ll have left.', ru: 'К твоему приходу меня уже не будет.' },
      { en: 'She\'ll have been here for a decade next year.', ru: 'В следующем году будет десять лет, как она здесь.' },
      { en: 'In an hour we\'ll be landing.', ru: 'Через час будем садиться на посадку.' },
    ],
    pitfalls: [
      'I will have finish → I will have finished.',
      'Путать с Present Perfect: I\'ll have done it by Monday — будущее; I\'ve done it — уже сейчас.',
      'Will you use the car this evening? грубее, чем Will you be using… в просьбе занять ресурс.',
    ],
    seeAlso: ['b1-future-forms', 'a2-will-going-to', 'b1-pp-continuous'],
  },
  {
    id: 'b2-non-defining-relative',
    level: 'B2',
    title: 'Non-defining relative clauses',
    gist: 'Добавочная информация про уже известный объект. Запятые обязательны. Who/which, не that. Нельзя опустить местоимение.',
    form: ', who/which/whose/where …, · which может относиться ко всему предложению',
    rules: [
      'My sister, who lives in Oslo, is a chemist. Сестра одна; придаточное не выбирает её из толпы.',
      'That запрещён: *My sister, that lives… London, which is huge, …',
      'Which ко всему факту: He quit, which surprised everyone.',
      'Не сокращается как defining: нельзя *My sister, lives in Oslo, is…',
    ],
    examples: [
      { en: 'Berlin, which I visited in May, was packed.', ru: 'Берлин, в котором я был в мае, был забит.' },
      { en: 'Sam, whose desk is next to mine, is away.', ru: 'Сэм, чей стол рядом с моим, отсутствует.' },
      { en: 'The film, which came out last year, won three awards.', ru: 'Фильм, вышедший в прошлом году, взял три награды.' },
      { en: 'She declined, which was a shame.', ru: 'Она отказалась, что было жаль.' },
      { en: 'Our office, where I spend most weekdays, is being renovated.', ru: 'Наш офис, где я провожу будни, ремонтируют.' },
    ],
    pitfalls: [
      'Забыть запятые — фраза читается как defining и меняет смысл («сестра, которая в Осло» = возможно, их несколько).',
      'That после запятой.',
      'Who вместо which для вещей: the book, who… → which.',
    ],
    seeAlso: ['b1-defining-relative', 'a2-relative-basic', 'b2-participle-clauses'],
  },
  {
    id: 'b2-participle-clauses',
    level: 'B2',
    title: 'Participle clauses',
    gist: 'Сжатие: Walking down the street, I saw her. Having finished, we left. Нужно общее подлежащее, иначе получится dangling modifier.',
    form: 'V-ing (одновременно / причина) · V3 (пассив / завершённость) · having + V3 (раньше) · being + V3',
    rules: [
      'Feeling tired, she sat down. = Because she felt tired… Подлежащее she относится к причастию.',
      'Built in 1900, the bridge is still used. (пассивный смысл).',
      'Having lost the keys, I waited outside. Сначала потеря, потом ожидание.',
      'Ошибка: Walking down the street, a brick fell on me. Кирпич не гулял. Нужно As I was walking… / Walking down the street, I was hit by a brick.',
    ],
    examples: [
      { en: 'Looking out of the window, he noticed a taxi.', ru: 'Глядя в окно, он заметил такси.' },
      { en: 'Shocked by the news, she said nothing.', ru: 'Потрясённая новостью, она ничего не сказала.' },
      { en: 'Having checked the figures, we sent the file.', ru: 'Проверив цифры, мы отправили файл.' },
      { en: 'Not knowing the address, I called her.', ru: 'Не зная адреса, я ей позвонил.' },
      { en: 'Left in the sun, the chocolate melted.', ru: 'Оставленный на солнце, шоколад растаял.' },
    ],
    pitfalls: [
      'Разные подлежащие у причастия и главной части.',
      'Being tired, the work was hard — work не устал. Being tired, I found the work hard.',
      'Путать с герундием подлежащего: Swimming is healthy — это не participle clause.',
    ],
    seeAlso: ['b2-non-defining-relative', 'b1-defining-relative', 'a2-gerund-infinitive'],
  },
  {
    id: 'b2-remember-try',
    level: 'B2',
    title: 'Remember / stop / try: to vs -ing',
    gist: 'Один глагол — два смысла. To — часто намерение или следующий шаг. -ing — факт/воспоминание/прекращение самого действия.',
    form: 'remember/forget to V vs V-ing · stop to V vs V-ing · try to V vs V-ing · regret to V vs V-ing · mean to V vs V-ing',
    rules: [
      'Remember to lock = не забудь (ещё впереди). Remember locking = помню, что запирал.',
      'Stop smoking = бросить курить. Stop to smoke = остановиться, чтобы покурить.',
      'Try to open = пытаться (усилие). Try adding salt = попробуй как эксперимент.',
      'Regret to say = с сожалением сообщаю (формально). Regret saying = жалею, что сказал.',
    ],
    examples: [
      { en: 'Remember to email her.', ru: 'Не забудь ей написать.' },
      { en: 'I remember emailing her last week.', ru: 'Помню, что писал ей на прошлой неделе.' },
      { en: 'He stopped to tie his shoe.', ru: 'Он остановился, чтобы завязать шнурок.' },
      { en: 'Try restarting the app.', ru: 'Попробуй перезапустить приложение.' },
      { en: 'I regret to inform you that…', ru: 'С сожалением сообщаю, что…' },
    ],
    pitfalls: [
      'I forgot sending the file когда имелось «забыл отправить» → I forgot to send.',
      'Stop to smoke вместо «бросить» → stop smoking.',
      'Go on to V = перейти к следующему; go on V-ing = продолжать то же.',
    ],
    seeAlso: ['b1-gerund-infinitive', 'a2-gerund-infinitive', 'b2-participle-clauses'],
  },
  {
    id: 'b2-inversion',
    level: 'B2',
    title: 'Inversion: Never / Hardly / Not only',
    gist: 'После отрицательного или ограничивающего наречия в начале — порядок как в вопросе. Формальный акцент, не повседневная болтовня.',
    form: 'Never / Rarely / Hardly / Seldom / Not only / No sooner + вспомогательный + подлежащее + …',
    rules: [
      'Never have I seen such a mess. = I have never seen…',
      'Hardly had we sat down when the fire alarm went off. No sooner had I left than it started to rain. (when vs than).',
      'Not only did she refuse, but she also left. Нужен did, если нет другого вспомогательного.',
      'Только если фраза стоит в начале. I have never… без инверсии.',
    ],
    examples: [
      { en: 'Rarely do we get a day like this.', ru: 'Редко выпадает такой день.' },
      { en: 'Not only was the hotel full, but the next one was too.', ru: 'Мало того что отель был полный — следующий тоже.' },
      { en: 'Hardly had I arrived when they started.', ru: 'Едва я приехал, как они начали.' },
      { en: 'Under no circumstances should you skip the backup.', ru: 'Ни при каких обстоятельствах не пропускай бэкап.' },
      { en: 'Little did they know what was coming.', ru: 'Они и не подозревали, что будет дальше.' },
    ],
    pitfalls: [
      'Never I have seen → Never have I seen.',
      'No sooner … when → No sooner … than. Hardly … than → Hardly … when.',
      'Ставить инверсию после never в середине: I never have I… — ломает фразу.',
    ],
    seeAlso: ['b2-discourse', 'b1-pp-vs-past', 'b2-wish-if-only'],
  },
  {
    id: 'b2-discourse',
    level: 'B2',
    title: 'Связки дискурса',
    gist: 'Слова, которые держат аргумент: добавление, контраст, причина, итог. На B2 важны позиция в предложении и пунктуация, не длинный список синонимов.',
    form: 'however / therefore / moreover (часто с ; или . ) · although + clause · because / so · on the other hand · as a result · in terms of',
    rules: [
      'However / therefore / moreover / nevertheless — linking adverbs: точка или ; перед ними, запятая после в начале предложения.',
      'So / and / but — между частями проще, без «.; However,» обязательно.',
      'On the one hand … on the other (hand) — два полюса. Whereas / while — контраст фактов в одном предложении.',
      'In terms of cost… As for… Speaking of… — смена аспекта. Anyway / still — разговорный поворот.',
    ],
    examples: [
      { en: 'The idea is cheap. However, it is risky.', ru: 'Идея дешёвая. Однако она рискованная.' },
      { en: 'Demand rose; therefore prices went up.', ru: 'Спрос вырос; поэтому цены поднялись.' },
      { en: 'The job is remote, whereas mine is not.', ru: 'Работа удалённая, тогда как моя — нет.' },
      { en: 'In terms of timing, Friday is better.', ru: 'По срокам пятница лучше.' },
      { en: 'It was raining, so we stayed in.', ru: 'Шёл дождь, поэтому мы остались дома.' },
    ],
    pitfalls: [
      'Although + however в одном каркасе: Although it was late, however we stayed — выбери одно.',
      'Because + запятая + полное предложение без главного: Because I was tired. — обрывок.',
      'On the other hand без первой руки — нормально, но не как «и ещё плюс»; это контраст, не moreover.',
    ],
    seeAlso: ['b1-although-despite', 'b2-inversion', 'b2-non-defining-relative'],
  },
  {
    id: 'b2-had-better',
    level: 'B2',
    title: 'Had better / would rather',
    gist: 'Had better — «лучше бы», с оттенком последствия, если не сделаешь. Would rather — предпочтение. Обе без to.',
    form: 'had better (not) + V · would rather + V · would rather + Past Simple (чужое действие)',
    rules: [
      'You\'d better leave now. You\'d better not be late. Это не прошлое had; отрицание: better not, не hadn\'t better в обычной речи.',
      'Сильнее should, слабее must. Часто предупреждение.',
      'I\'d rather walk. I\'d rather not talk about it. Чужое: I\'d rather you waited. (см. wish-блок).',
      'Ought to ≈ should, чуть формальнее: You ought to check the date.',
    ],
    examples: [
      { en: 'We\'d better book a table.', ru: 'Нам лучше забронировать стол.' },
      { en: 'You\'d better not ignore this email.', ru: 'Это письмо лучше не игнорировать.' },
      { en: 'I\'d rather take the earlier train.', ru: 'Я лучше возьму более ранний поезд.' },
      { en: 'I\'d rather not decide tonight.', ru: 'Я бы лучше не решал сегодня.' },
      { en: 'You ought to tell them the truth.', ru: 'Тебе следует сказать им правду.' },
    ],
    pitfalls: [
      'You had better to go → You had better go.',
      'You would better… → You had better… Would rather ≠ had better.',
      'Had better для вежливого совета незнакомцу звучит резко; should мягче.',
    ],
    seeAlso: ['a2-modals-obligation', 'b2-wish-if-only', 'b1-wish'],
  },
]
